name: opencode

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  opencode:
    if: |-
      (github.event_name == 'issues' && contains(github.event.issue.body, '/oc')) ||
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '/oc')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '/oc'))
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run opencode
        uses: anomalyco/opencode/github@latest
        env:
          OPENCODE_API_KEY: ${{ secrets.OPENCODE_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          model: opencode/x-preview-f-free
          use_github_token: true